# Generated by Django 6.1.1 on 2026-09-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_user_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
