# Generated by Django 6.1.1 on 2026-09-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_ordering_tiebreak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-is_pinned', '-last_posted_at', '-id']},
        ),
    ]
