# Generated by Django 6.1.1 on 2026-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_ordering_tiebreak'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='forum',
            name='forum_in_category_xor_parent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('parent__isnull', True)), models.Q(('category__isnull', True), ('parent__isnull', False)), _connector='OR'), name='forum_in_category_xor_parent', violation_error_message='A forum needs either a category (top level) or a parent forum (subforum), but not both.'),
        ),
    ]
