# Generated by Django 6.1.1 on 2026-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_user_post_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumbnail_1600',
            field=models.ImageField(blank=True, editable=False, upload_to='attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumbnail_800',
            field=models.ImageField(blank=True, editable=False, upload_to='attachments/%Y/%m/'),
        ),
    ]
