# Generated by Django 6.1.1 on 2026-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_attachment_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='draft_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32),
        ),
    ]
