# Generated by Django 6.1.1 on 2026-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_attachment_draft_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, editable=False, upload_to='avatars/', verbose_name='profile photo'),
        ),
    ]
